// ed-throughput pack — 25 agents for ED Throughput.
// Generated by scripts/gen-vertical-packs.mjs
import type { DomainPack } from '../../src/control-plane/pack-registry.js';

export const edThroughputPack: DomainPack = Object.freeze({
  id: 'ed-throughput',
  version: '1.0.0',
  extends: [{ id: 'healthcare-core', versionRange: '^0.2.0' }],
  appliesTo: { organizationKinds: ['provider', 'health-system', 'practice'], facilityKinds: ['emergency-department', 'hospital'] },
  capabilities: ['esi-triage', 'bed-flow', 'boarding-mgmt', 'emtala', 'sepsis-alert'],
  cmsUniverse: [],
  requiredControls: ['audit-provenance', 'phi-handling', 'access-policy'],
});
