// home-health pack — 35 agents for Home Health.
// Generated by scripts/gen-vertical-packs.mjs
import type { DomainPack } from '../../src/control-plane/pack-registry.js';

export const homeHealthPack: DomainPack = Object.freeze({
  id: 'home-health',
  version: '1.0.0',
  extends: [{ id: 'healthcare-core', versionRange: '^0.2.0' }],
  appliesTo: { organizationKinds: ['provider', 'health-system', 'practice'], facilityKinds: ['home-health', 'home-based'] },
  capabilities: ['oasis-e', 'pdgm-billing', 'visit-routing', 'telemonitoring', 'wound-care', 'fall-prevention-home'],
  cmsUniverse: [],
  requiredControls: ['audit-provenance', 'phi-handling', 'access-policy'],
});
