// hospital-at-home pack — 25 agents for Hospital-at-Home.
// Generated by scripts/gen-vertical-packs.mjs
import type { DomainPack } from '../../src/control-plane/pack-registry.js';

export const hospitalAtHomePack: DomainPack = Object.freeze({
  id: 'hospital-at-home',
  version: '1.0.0',
  extends: [{ id: 'healthcare-core', versionRange: '^0.2.0' }],
  appliesTo: { organizationKinds: ['provider', 'health-system', 'practice'], facilityKinds: ['hospital-at-home', 'hospital'] },
  capabilities: ['h-at-h-eligibility', 'remote-telemetry', 'escalation-plan', 'in-home-clinical-team'],
  cmsUniverse: [],
  requiredControls: ['audit-provenance', 'phi-handling', 'access-policy'],
});
