// Auto-generated by entity-compiler. Register in packs/index.ts after review.
import type { DomainPack } from '../../src/control-plane/pack-registry.js';

export const mixedSampleClinicPack: DomainPack = Object.freeze({
  id: 'mixed-sample-clinic',
  version: '1.0.0',
  extends: [{ id: 'healthcare-core', versionRange: '^0.2.0' }],
  appliesTo: { organizationKinds: ['provider', 'health-system', 'practice'], facilityKinds: ["primary-care","outpatient"] },
  capabilities: ["entity-derived"],
  cmsUniverse: [],
  requiredControls: ['access-policy', 'audit-provenance', 'phi-handling', 'billing-metering'],
});
