// CMS measure catalog seeds.
//
// Every entry cites the source CMS specification and includes the fields the
// harness's measure engine needs to run: denominator, numerator, exclusions,
// stratifications, evidence requirements. Facility-level thresholds and
// benchmarks live in `facility_config` (category = 'measure') and override
// these defaults.
//
// This file is the "batteries included" set. Additional measures can be
// registered at runtime via `CMSSourceRegistry.registerMeasure(...)`.

import type { CMSMeasureSpec } from './cms-source-registry.js';

const SRC = (path: string): string => `https://www.cms.gov/${path}`;

// ---- ESRD-QIP PY-2027 clinical + reporting measures ----
export const ESRD_QIP_MEASURES: readonly CMSMeasureSpec[] = Object.freeze([
  {
    id: 'cms:esrd-qip:kt-v',
    title: 'ESRD-QIP: Kt/V Dialysis Adequacy Comprehensive',
    programId: 'cms:esrd:qip',
    version: 'PY-2027',
    effectiveFrom: '2027-01-01',
    reportingPeriod: 'monthly',
    calculationMethod: 'proportion',
    denominator: { description: 'Adult and pediatric ESRD patients with 4+ months on HD or PD in the facility during the month', valueSetIds: ['vs:esrd-patients-in-facility'] },
    numerator: { description: 'Patients whose delivered dose met adequacy: HD spKt/V ≥ 1.2 or PD weekly Kt/V ≥ 1.7', valueSetIds: ['vs:kt-v-adequate'], timeWindowDays: 30 },
    exclusions: [
      { description: 'Patients transient/traveling with <4 months at facility', valueSetIds: ['vs:transient-patients'] },
      { description: 'Patients enrolled in hospice during month', valueSetIds: ['vs:hospice-enrolled'] },
    ],
    stratifications: ['modality:HD', 'modality:PD', 'age:adult', 'age:pediatric'],
    evidenceRequirements: ['clinical:kt-v-value', 'clinical:modality', 'admin:facility-months'],
    source: { url: SRC('medicare/quality/esrd') },
  },
  {
    id: 'cms:esrd-qip:vat',
    title: 'ESRD-QIP: Vascular Access Type Clinical',
    programId: 'cms:esrd:qip',
    version: 'PY-2027',
    effectiveFrom: '2027-01-01',
    reportingPeriod: 'monthly',
    calculationMethod: 'proportion',
    denominator: { description: 'Adult HD patients with 90+ days on dialysis', valueSetIds: ['vs:adult-hd-90d'] },
    numerator: { description: 'Patients whose vascular access was AVF only at last HD session in the month', valueSetIds: ['vs:avf-only'] },
    exclusions: [{ description: 'Patients hospitalized entire month', valueSetIds: ['vs:hospitalized-full-month'] }],
    stratifications: ['sex', 'age-group'],
    evidenceRequirements: ['clinical:vascular-access-type', 'admin:hd-vintage-days'],
    source: { url: SRC('medicare/quality/esrd') },
  },
  {
    id: 'cms:esrd-qip:hypercalcemia',
    title: 'ESRD-QIP: Hypercalcemia Clinical',
    programId: 'cms:esrd:qip',
    version: 'PY-2027',
    effectiveFrom: '2027-01-01',
    reportingPeriod: 'monthly',
    calculationMethod: 'proportion',
    denominator: { description: 'Adult ESRD patients receiving in-center HD or home dialysis with a serum calcium result in the month', valueSetIds: ['vs:adult-esrd-with-ca-lab'] },
    numerator: { description: 'Patient-months with 3-month rolling mean serum calcium > 10.2 mg/dL', valueSetIds: ['vs:serum-calcium-elevated'], timeWindowDays: 90 },
    exclusions: [],
    stratifications: ['modality'],
    evidenceRequirements: ['lab:serum-calcium', 'admin:modality'],
    source: { url: SRC('medicare/quality/esrd') },
  },
  {
    id: 'cms:esrd-qip:sti',
    title: 'ESRD-QIP: Standardized Transfusion Ratio (STrR)',
    programId: 'cms:esrd:qip',
    version: 'PY-2027',
    effectiveFrom: '2027-01-01',
    reportingPeriod: 'annually',
    calculationMethod: 'ratio',
    denominator: { description: 'Expected transfusions based on national rate and facility case-mix', valueSetIds: ['vs:transfusion-expected'] },
    numerator: { description: 'Observed eligible red blood cell transfusions in ESRD patients at the facility', valueSetIds: ['vs:transfusion-observed'] },
    exclusions: [{ description: 'Transfusions during hospitalization for sickle cell / hemolytic anemia', valueSetIds: ['vs:sickle-cell-hemolytic'] }],
    stratifications: [],
    evidenceRequirements: ['claims:transfusion-events', 'admin:patient-months'],
    source: { url: SRC('medicare/quality/esrd') },
  },
  {
    id: 'cms:esrd-qip:srr',
    title: 'ESRD-QIP: Standardized Readmission Ratio (SRR)',
    programId: 'cms:esrd:qip',
    version: 'PY-2027',
    effectiveFrom: '2027-01-01',
    reportingPeriod: 'annually',
    calculationMethod: 'ratio',
    denominator: { description: 'Expected 30-day unplanned readmissions per national model', valueSetIds: ['vs:readmit-expected'] },
    numerator: { description: 'Observed 30-day unplanned readmissions after index discharge', valueSetIds: ['vs:readmit-observed'] },
    exclusions: [{ description: 'Planned readmissions, transfers, discharges against medical advice', valueSetIds: ['vs:readmit-excluded'] }],
    stratifications: [],
    evidenceRequirements: ['claims:inpatient-admits', 'claims:discharge-disposition'],
    source: { url: SRC('medicare/quality/esrd') },
  },
  {
    id: 'cms:esrd-qip:shr',
    title: 'ESRD-QIP: Standardized Hospitalization Ratio (SHR)',
    programId: 'cms:esrd:qip',
    version: 'PY-2027',
    effectiveFrom: '2027-01-01',
    reportingPeriod: 'annually',
    calculationMethod: 'ratio',
    denominator: { description: 'Expected hospitalizations per national model + case-mix adjustment', valueSetIds: ['vs:hosp-expected'] },
    numerator: { description: 'Observed hospitalizations in facility during measurement year', valueSetIds: ['vs:hosp-observed'] },
    exclusions: [],
    stratifications: [],
    evidenceRequirements: ['claims:inpatient-admits', 'admin:patient-months'],
    source: { url: SRC('medicare/quality/esrd') },
  },
  {
    id: 'cms:esrd-qip:smr',
    title: 'ESRD-QIP: Standardized Mortality Ratio (SMR)',
    programId: 'cms:esrd:qip',
    version: 'PY-2027',
    effectiveFrom: '2027-01-01',
    reportingPeriod: 'annually',
    calculationMethod: 'ratio',
    denominator: { description: 'Expected deaths per national model + case-mix adjustment', valueSetIds: ['vs:mortality-expected'] },
    numerator: { description: 'Observed deaths in facility during measurement year', valueSetIds: ['vs:mortality-observed'] },
    exclusions: [],
    stratifications: [],
    evidenceRequirements: ['registry:crownweb-deaths', 'admin:patient-years'],
    source: { url: SRC('medicare/quality/esrd') },
  },
  {
    id: 'cms:esrd-qip:pain-assessment',
    title: 'ESRD-QIP: Pain Assessment and Follow-Up (Reporting)',
    programId: 'cms:esrd:qip',
    version: 'PY-2027',
    effectiveFrom: '2027-01-01',
    reportingPeriod: 'monthly',
    calculationMethod: 'proportion',
    denominator: { description: 'Adult ESRD patient-months', valueSetIds: ['vs:adult-esrd-months'] },
    numerator: { description: 'Patient-months with documented pain assessment AND, if positive, a documented follow-up plan', valueSetIds: ['vs:pain-assessed-and-followed'] },
    exclusions: [],
    stratifications: [],
    evidenceRequirements: ['clinical:pain-screen', 'clinical:pain-plan'],
    source: { url: SRC('medicare/quality/esrd') },
  },
  {
    id: 'cms:esrd-qip:depression-screening',
    title: 'ESRD-QIP: Clinical Depression Screening and Follow-Up (Reporting)',
    programId: 'cms:esrd:qip',
    version: 'PY-2027',
    effectiveFrom: '2027-01-01',
    reportingPeriod: 'annually',
    calculationMethod: 'proportion',
    denominator: { description: 'Adult ESRD patients aged 12+ during measurement year', valueSetIds: ['vs:esrd-age-12plus'] },
    numerator: { description: 'Patients screened with a standardized tool and, if positive, documented plan', valueSetIds: ['vs:depression-screened-and-planned'] },
    exclusions: [{ description: 'Patient refusal', valueSetIds: ['vs:patient-refusal'] }],
    stratifications: [],
    evidenceRequirements: ['clinical:phq-score', 'clinical:depression-plan'],
    source: { url: SRC('medicare/quality/esrd') },
  },
  {
    id: 'cms:esrd-qip:nhsn-bsi',
    title: 'ESRD-QIP: NHSN Bloodstream Infection in Hemodialysis Outpatients',
    programId: 'cms:esrd:qip',
    version: 'PY-2027',
    effectiveFrom: '2027-01-01',
    reportingPeriod: 'monthly',
    calculationMethod: 'ratio',
    denominator: { description: 'Hemodialysis patient-months in outpatient facility', valueSetIds: ['vs:hd-patient-months'] },
    numerator: { description: 'Positive blood cultures meeting NHSN Dialysis Event criteria', valueSetIds: ['vs:nhsn-bsi-events'] },
    exclusions: [],
    stratifications: ['access-type:AVF', 'access-type:AVG', 'access-type:catheter'],
    evidenceRequirements: ['nhsn:bsi-event', 'admin:hd-patient-months'],
    source: { url: 'https://www.cdc.gov/nhsn/dialysis/index.html' },
  },
  {
    id: 'cms:esrd-qip:iccbba',
    title: 'ESRD-QIP: Ultrafiltration Rate Reporting (Reporting)',
    programId: 'cms:esrd:qip',
    version: 'PY-2027',
    effectiveFrom: '2027-01-01',
    reportingPeriod: 'monthly',
    calculationMethod: 'proportion',
    denominator: { description: 'Adult HD patient-months with 3+ HD treatments in month', valueSetIds: ['vs:adult-hd-with-3-plus-tx'] },
    numerator: { description: 'Patient-months with UFR reported for each HD session, expressed in mL/kg/hr', valueSetIds: ['vs:ufr-reported'] },
    exclusions: [],
    stratifications: [],
    evidenceRequirements: ['clinical:ufr-per-session', 'clinical:post-weight'],
    source: { url: SRC('medicare/quality/esrd') },
  },
  {
    id: 'cms:esrd-qip:phosphorus-reporting',
    title: 'ESRD-QIP: Serum Phosphorus Reporting (Reporting)',
    programId: 'cms:esrd:qip',
    version: 'PY-2027',
    effectiveFrom: '2027-01-01',
    reportingPeriod: 'monthly',
    calculationMethod: 'proportion',
    denominator: { description: 'Adult ESRD patient-months with 1+ month at facility', valueSetIds: ['vs:adult-esrd-months'] },
    numerator: { description: 'Patient-months with reported serum phosphorus value', valueSetIds: ['vs:phosphorus-reported'] },
    exclusions: [],
    stratifications: [],
    evidenceRequirements: ['lab:serum-phosphorus'],
    source: { url: SRC('medicare/quality/esrd') },
  },
  {
    id: 'cms:esrd-qip:facility-commitment',
    title: 'ESRD-QIP: Facility Commitment to Health Equity (Reporting)',
    programId: 'cms:esrd:qip',
    version: 'PY-2027',
    effectiveFrom: '2027-01-01',
    reportingPeriod: 'annually',
    calculationMethod: 'proportion',
    denominator: { description: 'Facility attests annually', valueSetIds: ['vs:facility-attestation'] },
    numerator: { description: 'Facility met all 5 domains of the Health Equity attestation', valueSetIds: ['vs:health-equity-attested'] },
    exclusions: [],
    stratifications: [],
    evidenceRequirements: ['admin:attestation-form'],
    source: { url: SRC('medicare/quality/esrd') },
  },
  {
    id: 'cms:esrd-qip:screening-sdoh',
    title: 'ESRD-QIP: Screening for Social Drivers of Health (Reporting)',
    programId: 'cms:esrd:qip',
    version: 'PY-2027',
    effectiveFrom: '2027-01-01',
    reportingPeriod: 'annually',
    calculationMethod: 'proportion',
    denominator: { description: 'Adult ESRD patients seen 1+ time in facility during measurement year', valueSetIds: ['vs:adult-esrd-seen'] },
    numerator: { description: 'Patients screened for 5 SDOH domains: food, housing, transportation, utilities, interpersonal safety', valueSetIds: ['vs:sdoh-screened-5-domain'] },
    exclusions: [{ description: 'Patient refusal', valueSetIds: ['vs:patient-refusal'] }],
    stratifications: [],
    evidenceRequirements: ['clinical:sdoh-screening'],
    source: { url: SRC('medicare/quality/esrd') },
  },
  {
    id: 'cms:esrd-qip:screen-positive-sdoh',
    title: 'ESRD-QIP: Screen Positive Rate for SDOH (Reporting)',
    programId: 'cms:esrd:qip',
    version: 'PY-2027',
    effectiveFrom: '2027-01-01',
    reportingPeriod: 'annually',
    calculationMethod: 'proportion',
    denominator: { description: 'Adult ESRD patients screened via cms:esrd-qip:screening-sdoh', valueSetIds: ['vs:sdoh-screened-5-domain'] },
    numerator: { description: 'Patients who screened positive in 1+ SDOH domain', valueSetIds: ['vs:sdoh-positive'] },
    exclusions: [],
    stratifications: ['domain'],
    evidenceRequirements: ['clinical:sdoh-screening'],
    source: { url: SRC('medicare/quality/esrd') },
  },
]);

// ---- Hospital IQR core clinical + PC measures ----
export const HOSPITAL_IQR_MEASURES: readonly CMSMeasureSpec[] = Object.freeze([
  {
    id: 'cms:iqr:ami-30d-mortality',
    title: 'IQR: 30-day Mortality after AMI',
    programId: 'cms:iqr',
    version: 'FY-2027',
    effectiveFrom: '2026-10-01',
    reportingPeriod: 'annually',
    calculationMethod: 'ratio',
    denominator: { description: 'FFS Medicare beneficiaries 65+ discharged with AMI', valueSetIds: ['vs:iqr-ami-index'] },
    numerator: { description: 'Deaths within 30 days of admission', valueSetIds: ['vs:death-30d'] },
    exclusions: [{ description: 'Transferred to another acute care', valueSetIds: ['vs:iqr-transfer-out'] }],
    stratifications: [],
    evidenceRequirements: ['claims:ami-diag', 'claims:mortality-link'],
    source: { url: SRC('medicare/quality/hospital-iqr') },
  },
  {
    id: 'cms:iqr:hf-30d-readmit',
    title: 'IQR: 30-day Readmission after HF',
    programId: 'cms:iqr',
    version: 'FY-2027',
    effectiveFrom: '2026-10-01',
    reportingPeriod: 'annually',
    calculationMethod: 'ratio',
    denominator: { description: 'FFS Medicare beneficiaries 65+ discharged with heart failure', valueSetIds: ['vs:iqr-hf-index'] },
    numerator: { description: 'Unplanned readmissions within 30 days of discharge', valueSetIds: ['vs:readmit-30d-unplanned'] },
    exclusions: [{ description: 'Planned readmissions', valueSetIds: ['vs:planned-readmit'] }],
    stratifications: ['duals-status'],
    evidenceRequirements: ['claims:hf-diag', 'claims:readmit'],
    source: { url: SRC('medicare/quality/hospital-iqr') },
  },
  {
    id: 'cms:iqr:sep-1',
    title: 'IQR: SEP-1 Severe Sepsis and Septic Shock: Management Bundle',
    programId: 'cms:iqr',
    version: 'FY-2027',
    effectiveFrom: '2026-10-01',
    reportingPeriod: 'quarterly',
    calculationMethod: 'proportion',
    denominator: { description: 'Adult inpatients with severe sepsis or septic shock present on admission', valueSetIds: ['vs:severe-sepsis-shock'] },
    numerator: { description: 'Cases receiving the SEP-1 bundle within required time windows', valueSetIds: ['vs:sep-1-bundle-complete'] },
    exclusions: [{ description: 'Directive against interventions / comfort care', valueSetIds: ['vs:comfort-care'] }],
    stratifications: [],
    evidenceRequirements: ['clinical:lactate', 'clinical:blood-cultures', 'clinical:antibiotic', 'clinical:crystalloid'],
    source: { url: SRC('medicare/quality/hospital-iqr') },
  },
  {
    id: 'cms:iqr:ce-imaging',
    title: 'IQR: Cataract: Complications Within 30 Days Requiring Additional Surgery',
    programId: 'cms:iqr',
    version: 'FY-2027',
    effectiveFrom: '2026-10-01',
    reportingPeriod: 'annually',
    calculationMethod: 'proportion',
    denominator: { description: 'Cataract surgery episodes', valueSetIds: ['vs:cataract-surgery'] },
    numerator: { description: 'Episodes with additional surgery within 30 days for complication', valueSetIds: ['vs:cataract-complication-surgery'] },
    exclusions: [],
    stratifications: [],
    evidenceRequirements: ['claims:cataract-cpt', 'claims:complication-cpt'],
    source: { url: SRC('medicare/quality/hospital-iqr') },
  },
]);

// ---- Hospital VBP domain measures ----
export const HOSPITAL_VBP_MEASURES: readonly CMSMeasureSpec[] = Object.freeze([
  {
    id: 'cms:vbp:hcahps-communication-nurses',
    title: 'HVBP: HCAHPS - Nurse Communication',
    programId: 'cms:hvbp',
    version: 'FY-2027',
    effectiveFrom: '2026-10-01',
    reportingPeriod: 'annually',
    calculationMethod: 'proportion',
    denominator: { description: 'HCAHPS respondents at hospital', valueSetIds: ['vs:hcahps-respondents'] },
    numerator: { description: 'Top-box "Always" responses to nurse communication questions', valueSetIds: ['vs:hcahps-nurse-top-box'] },
    exclusions: [],
    stratifications: [],
    evidenceRequirements: ['survey:hcahps'],
    source: { url: SRC('medicare/quality/value-based-programs/hvbp') },
  },
  {
    id: 'cms:vbp:mspb',
    title: 'HVBP: Medicare Spending Per Beneficiary (MSPB)',
    programId: 'cms:hvbp',
    version: 'FY-2027',
    effectiveFrom: '2026-10-01',
    reportingPeriod: 'annually',
    calculationMethod: 'ratio',
    denominator: { description: 'Expected MSPB (national + case-mix)', valueSetIds: ['vs:mspb-expected'] },
    numerator: { description: 'Observed price-standardized MSPB', valueSetIds: ['vs:mspb-observed'] },
    exclusions: [],
    stratifications: [],
    evidenceRequirements: ['claims:episode-spend'],
    source: { url: SRC('medicare/quality/value-based-programs/hvbp') },
  },
]);

// ---- MIPS quality, PI, cost, IA (representative set) ----
export const MIPS_MEASURES: readonly CMSMeasureSpec[] = Object.freeze([
  {
    id: 'cms:mips:q001-dm-hba1c',
    title: 'MIPS Quality #001 - Diabetes: Hemoglobin A1c (HbA1c) Poor Control (>9%)',
    programId: 'cms:mips',
    version: '2026',
    effectiveFrom: '2026-01-01',
    reportingPeriod: 'annually',
    calculationMethod: 'proportion',
    denominator: { description: 'Patients 18-75 with diabetes seen in the measurement period', valueSetIds: ['vs:mips-dm-index'], ageRange: { min: 18, max: 75 } },
    numerator: { description: 'Patients whose most recent HbA1c > 9% or missing', valueSetIds: ['vs:hba1c-gt-9-or-missing'] },
    exclusions: [{ description: 'Hospice or death during period', valueSetIds: ['vs:hospice-or-death'] }],
    stratifications: [],
    evidenceRequirements: ['lab:hba1c'],
    source: { url: 'https://qpp.cms.gov/mips/quality-measures' },
  },
  {
    id: 'cms:mips:q236-htn-control',
    title: 'MIPS Quality #236 - Controlling High Blood Pressure',
    programId: 'cms:mips',
    version: '2026',
    effectiveFrom: '2026-01-01',
    reportingPeriod: 'annually',
    calculationMethod: 'proportion',
    denominator: { description: 'Patients 18-85 with essential hypertension diagnosis', valueSetIds: ['vs:htn-diagnosis'], ageRange: { min: 18, max: 85 } },
    numerator: { description: 'Patients whose most recent BP < 140/90', valueSetIds: ['vs:bp-controlled'] },
    exclusions: [{ description: 'End-stage renal disease / pregnancy / hospice', valueSetIds: ['vs:htn-excluded'] }],
    stratifications: [],
    evidenceRequirements: ['clinical:blood-pressure'],
    source: { url: 'https://qpp.cms.gov/mips/quality-measures' },
  },
  {
    id: 'cms:mips:pi-eprescribing',
    title: 'MIPS Promoting Interoperability - e-Prescribing',
    programId: 'cms:mips',
    version: '2026',
    effectiveFrom: '2026-01-01',
    reportingPeriod: 'annually',
    calculationMethod: 'proportion',
    denominator: { description: 'Prescriptions written during 90-day performance period', valueSetIds: ['vs:mips-rx-written'] },
    numerator: { description: 'Prescriptions transmitted electronically via CEHRT', valueSetIds: ['vs:mips-rx-eprescribed'] },
    exclusions: [{ description: 'Controlled substance exceptions', valueSetIds: ['vs:rx-controlled'] }],
    stratifications: [],
    evidenceRequirements: ['pi:cehrt-audit', 'admin:erx-log'],
    source: { url: 'https://qpp.cms.gov/mips/promoting-interoperability' },
  },
  {
    id: 'cms:mips:cost-tpcc',
    title: 'MIPS Cost - Total Per Capita Cost (TPCC)',
    programId: 'cms:mips',
    version: '2026',
    effectiveFrom: '2026-01-01',
    reportingPeriod: 'annually',
    calculationMethod: 'ratio',
    denominator: { description: 'Expected total per capita spend', valueSetIds: ['vs:tpcc-expected'] },
    numerator: { description: 'Observed total per capita spend attributable to clinician', valueSetIds: ['vs:tpcc-observed'] },
    exclusions: [],
    stratifications: [],
    evidenceRequirements: ['claims:episode-attribution'],
    source: { url: 'https://qpp.cms.gov/mips/cost' },
  },
  {
    id: 'cms:mips:ia-pspa19',
    title: 'MIPS Improvement Activity IA_PSPA_19 - Implementation of formal quality improvement methods',
    programId: 'cms:mips',
    version: '2026',
    effectiveFrom: '2026-01-01',
    reportingPeriod: 'annually',
    calculationMethod: 'proportion',
    denominator: { description: 'Attestation window', valueSetIds: ['vs:ia-attestation'] },
    numerator: { description: 'Formal QI methods deployed 90+ days', valueSetIds: ['vs:ia-qi-attested'] },
    exclusions: [],
    stratifications: [],
    evidenceRequirements: ['admin:qi-charter', 'admin:qi-outcomes'],
    source: { url: 'https://qpp.cms.gov/mips/improvement-activities' },
  },
]);

// ---- Promoting Interoperability (hospital) ----
export const PI_HOSPITAL_MEASURES: readonly CMSMeasureSpec[] = Object.freeze([
  {
    id: 'cms:pi-hospital:hie',
    title: 'PI (Hospital) - Health Information Exchange (Send + Receive + Reconcile)',
    programId: 'cms:promoting-interoperability',
    version: '2026',
    effectiveFrom: '2026-01-01',
    reportingPeriod: 'quarterly',
    calculationMethod: 'proportion',
    denominator: { description: 'Transitions of care initiated by hospital', valueSetIds: ['vs:transitions-out'] },
    numerator: { description: 'Transitions with electronic summary sent AND received AND reconciled', valueSetIds: ['vs:hie-send-receive-reconcile'] },
    exclusions: [],
    stratifications: [],
    evidenceRequirements: ['pi:cehrt-audit', 'admin:ehr-log'],
    source: { url: SRC('medicare/regulations-guidance/promoting-interoperability-programs') },
  },
]);

// ---- NHSN Dialysis Events (used by ESRD-QIP but also standalone reporting) ----
export const NHSN_MEASURES: readonly CMSMeasureSpec[] = Object.freeze([
  {
    id: 'nhsn:dialysis-event',
    title: 'NHSN - Dialysis Event Reporting',
    programId: 'nhsn:dialysis',
    version: '2026',
    effectiveFrom: '2026-01-01',
    reportingPeriod: 'monthly',
    calculationMethod: 'ratio',
    denominator: { description: 'Outpatient HD patient-months at facility', valueSetIds: ['vs:hd-patient-months'] },
    numerator: { description: 'Reported Dialysis Events: BSI, positive blood culture, or IV antimicrobial start', valueSetIds: ['vs:nhsn-de-events'] },
    exclusions: [],
    stratifications: ['event-type:BSI', 'event-type:PBC', 'event-type:IV-antimicrobial'],
    evidenceRequirements: ['nhsn:de-log'],
    source: { url: 'https://www.cdc.gov/nhsn/dialysis/index.html' },
  },
]);

// ---- CMS-0057-F Prior Authorization API/reporting ----
export const CMS_0057_F_MEASURES: readonly CMSMeasureSpec[] = Object.freeze([
  {
    id: 'cms:0057-f:pa-decision-time',
    title: 'CMS-0057-F: Prior Authorization Decision Timeliness',
    programId: 'cms:0057-f',
    version: '2024-final',
    effectiveFrom: '2027-01-01',
    reportingPeriod: 'annually',
    calculationMethod: 'proportion',
    denominator: { description: 'Prior authorization requests received', valueSetIds: ['vs:pa-received'] },
    numerator: { description: 'Requests decided within 72h (expedited) / 7 calendar days (standard)', valueSetIds: ['vs:pa-decided-in-sla'] },
    exclusions: [{ description: 'Drug PAs (excluded from rule scope)', valueSetIds: ['vs:pa-drug-excluded'] }],
    stratifications: ['urgency:expedited', 'urgency:standard'],
    evidenceRequirements: ['pa:request-log', 'pa:decision-log'],
    source: { url: 'https://www.federalregister.gov/documents/2024/02/08/2024-00895' },
  },
  {
    id: 'cms:0057-f:api-uptime',
    title: 'CMS-0057-F: Patient Access + Provider Access + Payer-to-Payer API Uptime',
    programId: 'cms:0057-f',
    version: '2024-final',
    effectiveFrom: '2027-01-01',
    reportingPeriod: 'quarterly',
    calculationMethod: 'proportion',
    denominator: { description: 'Total minutes in reporting period', valueSetIds: ['vs:period-minutes'] },
    numerator: { description: 'Minutes API responded within SLA (99.5% target)', valueSetIds: ['vs:api-uptime-minutes'] },
    exclusions: [],
    stratifications: ['api:patient-access', 'api:provider-access', 'api:payer-to-payer'],
    evidenceRequirements: ['ops:uptime-monitor'],
    source: { url: 'https://www.federalregister.gov/documents/2024/02/08/2024-00895' },
  },
]);

// ---- Aggregate seed ----
export const ALL_CMS_MEASURES: readonly CMSMeasureSpec[] = Object.freeze([
  ...ESRD_QIP_MEASURES,
  ...HOSPITAL_IQR_MEASURES,
  ...HOSPITAL_VBP_MEASURES,
  ...MIPS_MEASURES,
  ...PI_HOSPITAL_MEASURES,
  ...NHSN_MEASURES,
  ...CMS_0057_F_MEASURES,
]);
