// long-term-care pack — 35 agents for Long-Term Care / SNF.
// Generated by scripts/gen-vertical-packs.mjs
import type { DomainPack } from '../../src/control-plane/pack-registry.js';

export const longTermCarePack: DomainPack = Object.freeze({
  id: 'long-term-care',
  version: '1.0.0',
  extends: [{ id: 'healthcare-core', versionRange: '^0.2.0' }],
  appliesTo: { organizationKinds: ['provider', 'health-system', 'practice'], facilityKinds: ['snf', 'nursing-facility', 'assisted-living'] },
  capabilities: ['mds-3.0', 'pdpm-billing', 'care-plan-cadence', 'ltc-quality-measures', 'infection-preventionist'],
  cmsUniverse: [],
  requiredControls: ['audit-provenance', 'phi-handling', 'access-policy'],
});
