import type { ReplayEventSeed } from "./types";

const tenantId = "demo-renal-enterprise";
const base = {
  schemaVersion: "1.0.0",
  tenantId,
  purpose: "synthetic-enterprise-replay",
  classification: ["synthetic", "demo"],
};

export const runtimeReplayEvents: ReplayEventSeed[] = [
  {
    ...base,
    eventId: "evt-demo-discharge-001",
    eventType: "adt.discharge.v2",
    subject: { type: "patient", id: "SYN-10042" },
    validTime: "2026-08-21T12:14:00.000Z",
    recordedTime: "2026-08-21T12:14:02.114Z",
    correlationId: "OUT-RUNTIME-1042",
    source: { system: "synthetic-fhir-adapter", resource: "Encounter", version: "R4" },
    payload: { patientName: "Maya Ortiz", facilityId: "facility-franklin", discharged: true, nextTreatmentConfirmed: false, nextTreatmentAt: "2026-08-21T19:30:00.000Z" },
  },
  {
    ...base,
    eventId: "evt-demo-assessment-002",
    eventType: "assessment.response.v1",
    subject: { type: "patient", id: "SYN-10042" },
    validTime: "2026-08-18T16:20:00.000Z",
    recordedTime: "2026-08-21T12:14:03.302Z",
    correlationId: "OUT-RUNTIME-1042",
    causationId: "evt-demo-discharge-001",
    source: { system: "synthetic-assessment-service", resource: "QuestionnaireResponse", version: "3.1" },
    payload: { questionId: "transport-next-week", answer: "No. My daughter started night shift and cannot drive me on Tuesdays anymore.", structuredSeverity: 4, extractedConcept: "transportation-barrier", humanConfirmed: true },
  },
  {
    ...base,
    eventId: "evt-demo-assessment-011",
    eventType: "assessment.response.v1",
    subject: { type: "patient", id: "SYN-10042" },
    validTime: "2026-08-18T16:22:00.000Z",
    recordedTime: "2026-08-21T12:14:03.411Z",
    correlationId: "OUT-RUNTIME-1042",
    causationId: "evt-demo-assessment-002",
    source: { system: "synthetic-assessment-service", resource: "QuestionnaireResponse", version: "3.1" },
    payload: { questionId: "schedule-goal", answer: "I need to keep my morning work shift, so afternoon treatment is best for me.", extractedConcept: "afternoon-treatment-preference", preferredAfterLocal: "13:00", humanConfirmed: true },
  },
  {
    ...base,
    eventId: "evt-demo-capacity-003",
    eventType: "facility.capacity.changed.v2",
    subject: { type: "facility", id: "facility-franklin" },
    validTime: "2026-08-21T12:40:00.000Z",
    recordedTime: "2026-08-21T12:14:03.581Z",
    correlationId: "OUT-RUNTIME-1042",
    source: { system: "synthetic-facility-twin", resource: "ChairCapacity", version: "2" },
    payload: { availableChairAt: "2026-08-21T19:30:00.000Z", station: 4, staffRatioHeadroom: 0.4, machineReady: true, availableHours: 6.5 },
  },
  {
    ...base,
    eventId: "evt-demo-workforce-004",
    eventType: "staffing.coverage.changed.v1",
    subject: { type: "cohort", id: "region-middle-tennessee" },
    validTime: "2026-08-23T11:00:00.000Z",
    recordedTime: "2026-08-21T12:14:04.019Z",
    source: { system: "synthetic-workforce-service", resource: "CoverageForecast", version: "1" },
    payload: { shiftGaps: 11, affectedFacilities: ["facility-franklin", "facility-columbia", "facility-murfreesboro"], exposedTreatments: 43, credentialCompatibleFloatStaff: 7 },
  },
  {
    ...base,
    eventId: "evt-demo-quality-005",
    eventType: "quality.measure.changed.v1",
    subject: { type: "cohort", id: "region-middle-tennessee" },
    validTime: "2026-08-21T12:00:00.000Z",
    recordedTime: "2026-08-21T12:14:04.328Z",
    source: { system: "synthetic-quality-mart", resource: "AccessSurveillance", version: "2026.2" },
    payload: { measure: "long-term-catheter", currentPercent: 31.0, thresholdPercent: 25.0, affectedPatients: 31, tendernessMentions: 2 },
  },
  {
    ...base,
    eventId: "evt-demo-claim-006",
    eventType: "claim.status.changed.v2",
    subject: { type: "cohort", id: "division-southeast" },
    validTime: "2026-08-21T12:00:00.000Z",
    recordedTime: "2026-08-21T12:14:04.772Z",
    source: { system: "synthetic-revenue-cycle", resource: "ClaimStatus", version: "2" },
    payload: { cleanClaimVarianceDollars: 184000, rejectedRows: 118, suspectedMappingVersion: "fhir-r4.18" },
  },
  {
    ...base,
    eventId: "evt-demo-cms-007",
    eventType: "cms.submission.gap.v1",
    subject: { type: "submission", id: "PY2026-DIV-SE" },
    validTime: "2026-08-21T12:00:00.000Z",
    recordedTime: "2026-08-21T12:14:05.186Z",
    source: { system: "synthetic-measure-engine", resource: "SubmissionGap", version: "2026.2" },
    payload: { incompleteRows: 49, measurePackId: "ktv-comprehensive", suspectedMappingVersion: "fhir-r4.18", readinessBasisPoints: 9420 },
  },
  {
    ...base,
    eventId: "evt-demo-machine-008",
    eventType: "machine.maintenance.signal.v1",
    subject: { type: "cohort", id: "market-nashville-south" },
    validTime: "2026-08-24T12:00:00.000Z",
    recordedTime: "2026-08-21T12:14:05.631Z",
    source: { system: "synthetic-biomed-service", resource: "MaintenanceWindow", version: "1" },
    payload: { machinesDue: 3, chairHoursAtRisk: 18, safeWindows: 3 },
  },
  {
    ...base,
    eventId: "evt-demo-referral-009",
    eventType: "referral.received.v1",
    subject: { type: "cohort", id: "market-nashville-south" },
    validTime: "2026-08-21T12:10:00.000Z",
    recordedTime: "2026-08-21T12:14:06.047Z",
    source: { system: "synthetic-referral-service", resource: "Referral", version: "1" },
    payload: { newReferrals: 14, viableStarts: 9, requestedModality: "in-center" },
  },
  {
    ...base,
    eventId: "evt-demo-experience-010",
    eventType: "experience.response.v1",
    subject: { type: "cohort", id: "facility-franklin" },
    validTime: "2026-08-20T12:00:00.000Z",
    recordedTime: "2026-08-21T12:14:06.508Z",
    source: { system: "synthetic-experience-service", resource: "ResponseCluster", version: "1" },
    payload: { barrierClusters: 6, transportationMentions: 4, scheduleMentions: 2, humanReviewed: true },
  },
];
