/******************************************************************************
 *
 * Copyright (c) 2026 AnantHQ Inc.
 * All Rights Reserved.
 *
 * This software is licensed, not sold.
 *
 * The contents of this file constitute confidential and proprietary
 * information belonging exclusively to Unison Software Technologies Pvt. Ltd.
 *
 * This source code incorporates proprietary algorithms, software architecture,
 * business logic, computational methods, optimization techniques,
 * workflows, data structures, APIs, and implementation details that are
 * protected by copyright law, patent law, trade secret law, and
 * international intellectual property treaties.
 *
 * Except as expressly permitted by a written license agreement,
 * no person or organization may:
 *
 *   • Copy or reproduce this software.
 *   • Modify or create derivative works.
 *   • Reverse engineer, decompile, or disassemble.
 *   • Benchmark or publicly disclose performance.
 *   • Redistribute, sublicense, lease, rent, or sell.
 *   • Use this software for competitive analysis.
 *   • Disclose any implementation details.
 *
 * Any unauthorized use is strictly prohibited and may result in
 * civil damages, injunctive relief, criminal prosecution,
 * and all other remedies available under applicable law.
 *
 ******************************************************************************/

// PackWriter: materialize an AgentSpec[] into packs/<id>/{manifest.yaml, agents/*.yaml, index.ts}
// Idempotent: rewrites files on repeat runs. Does NOT modify packs/index.ts or bootstrap.ts
// automatically \u2014 the generated pack goes through the normal PackDraft review flow first.

import { mkdirSync, writeFileSync, existsSync, rmSync, readdirSync } from 'node:fs';
import { join } from 'node:path';
import { stringify as stringifyYaml } from 'yaml';
import type { AgentSpec } from '../agents/index.js';

export interface PackWriteOptions {
  packId: string;
  packVersion?: string;
  displayName?: string;
  extendsIds?: string[];
  facilityKinds?: string[];
  capabilities?: string[];
  outRoot?: string;  // default: 'packs/'
}

export interface WrittenPack {
  packDir: string;
  manifestPath: string;
  agentPaths: string[];
  indexPath: string;
}

export function writePack(agents: AgentSpec[], opts: PackWriteOptions): WrittenPack {
  const outRoot = opts.outRoot ?? 'packs';
  const packDir = join(outRoot, opts.packId);
  const agentsDir = join(packDir, 'agents');
  mkdirSync(agentsDir, { recursive: true });
  // Clean stale agent files so re-runs don't leave orphans
  for (const f of readdirSync(agentsDir)) {
    if (f.endsWith('.yaml')) rmSync(join(agentsDir, f));
  }
  const manifest = {
    id: opts.packId,
    version: opts.packVersion ?? '1.0.0',
    ...(opts.displayName ? { displayName: opts.displayName } : {}),
    extends: (opts.extendsIds ?? ['healthcare-core']).map((id) => ({ id, version_range: '^0.2.0' })),
    applies_to: {
      organization_kinds: ['provider', 'health-system', 'practice'],
      facility_kinds: opts.facilityKinds ?? ['primary-care', 'outpatient'],
    },
    capabilities: opts.capabilities ?? ['entity-derived'],
    required_controls: ['access-policy', 'audit-provenance', 'phi-handling'],
    provenance: {
      generatedBy: 'entity-compiler',
      generatedAt: new Date().toISOString(),
      agentCount: agents.length,
    },
  };
  const manifestPath = join(packDir, 'manifest.yaml');
  writeFileSync(manifestPath, stringifyYaml(manifest));

  const agentPaths: string[] = [];
  for (const a of agents) {
    const p = join(agentsDir, `${a.id}.yaml`);
    writeFileSync(p, stringifyYaml(a));
    agentPaths.push(p);
  }

  // Write a minimal index.ts consistent with existing packs
  const indexPath = join(packDir, 'index.ts');
  const facilityKindsLit = JSON.stringify(opts.facilityKinds ?? ['primary-care', 'outpatient']);
  const capsLit = JSON.stringify(opts.capabilities ?? ['entity-derived']);
  const indexTs = `// Auto-generated by entity-compiler. Register in packs/index.ts after review.
import type { DomainPack } from '../../src/control-plane/pack-registry.js';

export const ${camel(opts.packId)}Pack: DomainPack = Object.freeze({
  id: '${opts.packId}',
  version: '${opts.packVersion ?? '1.0.0'}',
  extends: [{ id: 'healthcare-core', versionRange: '^0.2.0' }],
  appliesTo: { organizationKinds: ['provider', 'health-system', 'practice'], facilityKinds: ${facilityKindsLit} },
  capabilities: ${capsLit},
  cmsUniverse: [],
  requiredControls: ['access-policy', 'audit-provenance', 'phi-handling', 'billing-metering'],
});
`;
  writeFileSync(indexPath, indexTs);

  return { packDir, manifestPath, agentPaths, indexPath };
}

export function packExists(packId: string, outRoot = 'packs'): boolean {
  return existsSync(join(outRoot, packId, 'manifest.yaml'));
}

function camel(s: string): string {
  return s.replace(/-([a-z])/g, (_, c: string) => c.toUpperCase());
}
