// oncology-deep pack — 40 agents for Oncology (deep).
// Generated by scripts/gen-vertical-packs.mjs
import type { DomainPack } from '../../src/control-plane/pack-registry.js';

export const oncologyDeepPack: DomainPack = Object.freeze({
  id: 'oncology-deep',
  version: '1.0.0',
  extends: [{ id: 'healthcare-core', versionRange: '^0.2.0' }],
  appliesTo: { organizationKinds: ['provider', 'health-system', 'practice'], facilityKinds: ['oncology', 'infusion', 'hospital'] },
  capabilities: ['chemo-safety', 'tumor-board-prep', 'symptom-triage', 'port-care', 'survivorship', 'clinical-trials-match'],
  cmsUniverse: [],
  requiredControls: ['audit-provenance', 'phi-handling', 'access-policy'],
});
