// radiology pack — 20 agents for Radiology.
// Generated by scripts/gen-vertical-packs.mjs
import type { DomainPack } from '../../src/control-plane/pack-registry.js';

export const radiologyPack: DomainPack = Object.freeze({
  id: 'radiology',
  version: '1.0.0',
  extends: [{ id: 'healthcare-core', versionRange: '^0.2.0' }],
  appliesTo: { organizationKinds: ['provider', 'health-system', 'practice'], facilityKinds: ['radiology', 'imaging-center', 'hospital'] },
  capabilities: ['worklist-priority', 'critical-result-comm', 'acr-appropriateness', 'peer-learning', 'contrast-safety'],
  cmsUniverse: [],
  requiredControls: ['audit-provenance', 'phi-handling', 'access-policy'],
});
