// revenue-cycle pack — 30 agents for Revenue Cycle.
// Generated by scripts/gen-vertical-packs.mjs
import type { DomainPack } from '../../src/control-plane/pack-registry.js';

export const revenueCyclePack: DomainPack = Object.freeze({
  id: 'revenue-cycle',
  version: '1.0.0',
  extends: [{ id: 'healthcare-core', versionRange: '^0.2.0' }],
  appliesTo: { organizationKinds: ['provider', 'health-system', 'practice'], facilityKinds: ['*'] },
  capabilities: ['denial-mgmt', 'coding-review', 'prior-auth', 'ar-aging', 'payment-posting', 'eligibility'],
  cmsUniverse: [],
  requiredControls: ['audit-provenance', 'phi-handling', 'access-policy'],
});
