/**
 * Generate the pack manifests that are missing, from the TypeScript descriptors.
 *
 * Nine of twenty-three pack directories shipped no `manifest.yaml`, so they
 * declared no surface at all and the platform could only report
 * `manifest.present: false`. A manifest is the artifact a second specialty
 * arrives through, and option B in the remaining-work analysis cannot even be
 * attempted while a third of the packs have none.
 *
 * GENERATED FROM THE DESCRIPTOR ON PURPOSE. `manifestDrift` compares version,
 * capabilities, requiredControls, appliesTo and cmsUniverse against the runtime
 * descriptor, and the runtime descriptor is what the registry actually resolves —
 * so hand-writing these would have produced nine files with subtly wrong
 * capability lists, which is exactly the defect the Phase 3 slice already found
 * three times. Deriving them makes drift zero by construction rather than by
 * care.
 *
 * Existing manifests are NEVER touched: this only fills a gap. Re-running it is
 * a no-op once every pack has one.
 *
 *   npx tsx scripts/generate-pack-manifests.ts
 */
import { existsSync, readdirSync, statSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';
import { fileURLToPath } from 'node:url';
import type { DomainPack } from '../src/control-plane/pack-registry.js';

const REPO_ROOT = fileURLToPath(new URL('..', import.meta.url));

const HEADER = `# Generated by scripts/generate-pack-manifests.ts from the runtime descriptor.
# Regenerate rather than hand-editing: manifestDrift compares this file to the
# descriptor in index.ts, and the descriptor is what the registry resolves.
`;

/** Single-quote YAML scalars that could otherwise be read as something else. */
const s = (v: string): string => (/^[A-Za-z0-9._:/@+-]+$/.test(v) ? v : `'${v.replace(/'/g, "''")}'`);

function render(pack: DomainPack): string {
  const lines: string[] = [HEADER, `id: ${s(pack.id)}`, `version: ${s(pack.version)}`];
  lines.push('entry: index.ts');

  if (pack.extends.length > 0) {
    lines.push('extends:');
    for (const e of pack.extends) lines.push(`  - id: ${s(e.id)}`, `    version_range: ${s(e.versionRange)}`);
  }
  lines.push('applies_to:');
  lines.push(`  organization_kinds: [${pack.appliesTo.organizationKinds.map(s).join(', ')}]`);
  if (pack.appliesTo.facilityKinds?.length) {
    lines.push(`  facility_kinds: [${pack.appliesTo.facilityKinds.map(s).join(', ')}]`);
  }

  lines.push(pack.capabilities.length ? 'capabilities:' : 'capabilities: []');
  for (const c of pack.capabilities) lines.push(`  - ${s(c)}`);

  if (pack.cmsUniverse.length === 0) {
    lines.push('cms_universe: []');
  } else {
    lines.push('cms_universe:');
    for (const c of pack.cmsUniverse) {
      lines.push(`  - id: ${s(c.id)}`, `    title: ${s(c.title)}`, `    authority: ${s(c.authority)}`);
      if (c.effectiveFrom) lines.push(`    effective_from: ${s(c.effectiveFrom)}`);
    }
  }

  lines.push(pack.requiredControls.length ? 'required_controls:' : 'required_controls: []');
  for (const c of pack.requiredControls) lines.push(`  - ${s(c)}`);

  // No `specialty:` block. These packs declare no ontology, events, workflows or
  // measures through the contract, and inventing sections here would turn
  // "declares nothing" into a claim — the conformance matrix would then report
  // them conformant on the strength of a file this script wrote.
  return `${lines.join('\n')}\n`;
}

/**
 * The descriptor for one pack directory, or a reason it has none.
 *
 * Enumerates DIRECTORIES rather than the `packs/index.ts` barrel, because the
 * barrel is the install list and this is about the pack catalog: six directories
 * carrying a real `DomainPack` descriptor are not installed (`dialysis-deep`,
 * `flagship-agents`, `policy-templates`, `primary-care-deep`, `research-pharma`,
 * `urgent-care-deep`), so a barrel-driven pass would have reported them as having
 * nothing to declare. They would have kept their `manifest.present: false`, and
 * the analysis would have kept counting nine.
 */
async function descriptorFor(packId: string): Promise<DomainPack | { error: string }> {
  try {
    const mod = (await import(`../packs/${packId}/index.js`)) as Record<string, unknown>;
    for (const value of Object.values(mod)) {
      const candidate = value as Partial<DomainPack> | undefined;
      if (!candidate || typeof candidate !== 'object') continue;
      if (typeof candidate.id !== 'string' || typeof candidate.version !== 'string') continue;
      if (!Array.isArray(candidate.capabilities)) continue;
      return candidate as DomainPack;
    }
    return { error: 'exports no DomainPack descriptor' };
  } catch (e) {
    return { error: e instanceof Error ? e.message : String(e) };
  }
}

const written: string[] = [];
const skipped: string[] = [];
const undecided: string[] = [];

for (const name of readdirSync(join(REPO_ROOT, 'packs')).sort()) {
  const dir = join(REPO_ROOT, 'packs', name);
  if (!statSync(dir).isDirectory()) continue;
  if (existsSync(join(dir, 'manifest.yaml'))) { skipped.push(name); continue; }

  const descriptor = await descriptorFor(name);
  if ('error' in descriptor) { undecided.push(`${name} (${descriptor.error})`); continue; }
  if (descriptor.id !== name) {
    undecided.push(`${name} (declares id "${descriptor.id}"; the directory is authoritative)`);
    continue;
  }
  writeFileSync(join(dir, 'manifest.yaml'), render(descriptor), 'utf8');
  written.push(name);
}

console.log(`wrote ${written.length}: ${written.join(', ') || '(none)'}`);
console.log(`kept  ${skipped.length}: ${skipped.join(', ') || '(none)'}`);
if (undecided.length) console.log(`no descriptor: ${undecided.join(', ')}`);
