// F2 — baseline comparison report.
//
//   npx tsx scripts/protocols-f2-report.ts [horizons]
//
// Runs the shared-state protocol heads against (a) persistence and (b) a fitted
// tabular baseline on a PATIENT-level split of the synthetic longitudinal
// glomerular simulator cohort, and prints the per-protocol / per-horizon table.
// Nothing here touches production data: the cohort is generated by
// src/simulator/longitudinal.ts.

import { runF2Evaluation } from '../src/protocols/shared-state.js';

const horizons = process.argv[2]
  ? process.argv[2].split(',').map((h) => Number.parseInt(h.trim(), 10)).filter((h) => Number.isFinite(h))
  : [7, 28];

const report = runF2Evaluation({ horizonsDays: horizons, salt: 'cli-report' });

console.log('F2 protocol-head evaluation (synthetic longitudinal cohort)');
console.log('  generated       ', report.generatedAt);
console.log('  rows            ', report.rows);
console.log('  split           ', `${report.patientLevelSplit.train.length} train / ${report.patientLevelSplit.test.length} test patients (no overlap: ${report.noPatientOverlap})`);
console.log('  coverage        ', report.coverage);
console.log('  summary         ', report.summary);
console.log('');
console.log('protocol'.padEnd(24), 'target'.padEnd(14), 'head'.padEnd(8), 'persist'.padEnd(8), 'baseline'.padEnd(8), 'vs persist', 'winner');
for (const head of report.regressionHeads) {
  console.log(
    head.protocol.padEnd(24),
    `${head.target}@${head.horizonDays}d`.padEnd(14),
    String(head.comparison.head.mae).padEnd(8),
    String(head.comparison.persistence.mae).padEnd(8),
    String(head.comparison.baseline?.mae ?? '-').padEnd(8),
    `${head.comparison.headVsPersistenceImprovementPct ?? '-'}%`.padEnd(10),
    head.comparison.winner,
  );
}
console.log('');
for (const cls of report.classificationHeads) {
  console.log(
    'classification'.padEnd(24),
    cls.target.padEnd(24),
    'state AUROC', String(cls.stateScoreMetrics.auroc).padEnd(8),
    'baseline AUROC', String(cls.baselineMetrics.auroc).padEnd(8),
    'ECE', cls.stateScoreMetrics.ece,
    '→', cls.winner,
  );
}

// exit non-zero when the shared-state heads fail the floor on most horizons,
// so the report can gate CI.
const degraded = report.summary.totalHeads > 0 && report.summary.headsBeatingPersistence < Math.ceil(report.summary.totalHeads * 0.75);
if (degraded) {
  console.error('\nFAIL: shared-state heads beat persistence on fewer than 75% of protocol×horizon pairs');
  process.exit(1);
}
