// behavioral-health pack — 30 agents for Behavioral Health.
// Generated by scripts/gen-vertical-packs.mjs
import type { DomainPack } from '../../src/control-plane/pack-registry.js';

export const behavioralHealthPack: DomainPack = Object.freeze({
  id: 'behavioral-health',
  version: '1.0.0',
  extends: [{ id: 'healthcare-core', versionRange: '^0.2.0' }],
  appliesTo: { organizationKinds: ['provider', 'health-system', 'practice'], facilityKinds: ['behavioral-health', 'primary-care', 'outpatient'] },
  capabilities: ['phq9-tracking', 'gad7-tracking', 'controlled-substance-mgmt', '42cfr-part2', 'crisis-triage', 'group-therapy-ops'],
  cmsUniverse: [],
  requiredControls: ['audit-provenance', 'phi-handling', 'access-policy'],
});
